// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX6mKNQKVv8hdHfr1gi4jNfoVPQF5i5hs',
    appId: '1:277843447662:web:eec177b0c7da6413c13b7f',
    messagingSenderId: '277843447662',
    projectId: 'trajan-food-app-78f9c',
    authDomain: 'trajan-food-app-78f9c.firebaseapp.com',
    databaseURL: 'https://trajan-food-app-78f9c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trajan-food-app-78f9c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfsem3YaneUNI4I2k7a_2laF_ipexGa6U',
    appId: '1:277843447662:android:338c58378f2b0293c13b7f',
    messagingSenderId: '277843447662',
    projectId: 'trajan-food-app-78f9c',
    databaseURL: 'https://trajan-food-app-78f9c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trajan-food-app-78f9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDacnMQcu4wBqVu_bUws2xjbXJwIdiipaM',
    appId: '1:277843447662:ios:90cbda873bdb7a12c13b7f',
    messagingSenderId: '277843447662',
    projectId: 'trajan-food-app-78f9c',
    databaseURL: 'https://trajan-food-app-78f9c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trajan-food-app-78f9c.appspot.com',
    iosBundleId: 'com.example.trajanFoodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDacnMQcu4wBqVu_bUws2xjbXJwIdiipaM',
    appId: '1:277843447662:ios:6e435ebe940485edc13b7f',
    messagingSenderId: '277843447662',
    projectId: 'trajan-food-app-78f9c',
    databaseURL: 'https://trajan-food-app-78f9c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'trajan-food-app-78f9c.appspot.com',
    iosBundleId: 'com.example.trajanFoodApp.RunnerTests',
  );
}
